<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VirtualController.Core\VirtualController.Core.csproj" />
    <ProjectReference Include="..\VirtualController.Windows\VirtualController.Windows.csproj" />
    <ProjectReference Include="..\VirtualController.Infrastructure\VirtualController.Infrastructure.csproj" />
    <ProjectReference Include="..\VirtualController.VirtualGamepad\VirtualController.VirtualGamepad.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
